# Generated by Django 4.2.6 on 2023-10-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuarios_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
