# Generated by Django 4.2.6 on 2023-10-17 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarios_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.role'),
        ),
    ]
